---
namespace: local
name: skopeo
version: 0.1.0

readme: README.md
authors:
  - Antonio Gravino <antoniogrv>
description: Interact with a local Skopeo installation within Ansible

license:
  - GPL-2.0-or-later
license_file: ""

tags: ["skopeo", "tools"]
dependencies: {}

repository: https://github.com/antoniogrv/ansible-skopeo-collection
documentation: |
  https://github.com/antoniogrv/ansible-skopeo-collection/blob/master/README.md
homepage: https://github.com/antoniogrv/ansible-skopeo-collection
issues: https://github.com/antoniogrv/ansible-skopeo-collection/issues
build_ignore: []
